import type { PocTemplate } from '../domain/types.js';

export const POC_TEMPLATES: PocTemplate[] = [
  {
    id: 'auth.role-diff.idor',
    name: 'Role Differential IDOR Review',
    category: 'auth',
    status: 'ready',
    description: 'Compare same-endpoint evidence across roles before proposing authorization or IDOR findings.',
    vulnerabilityClasses: ['CWE-639', 'CWE-862', 'IDOR', 'Broken Access Control'],
    requiredEvidence: ['http_exchange', 'command_output'],
    recommendedTools: ['credential.use_placeholder', 'browser.navigate', 'access.compare_evidence', 'finding.propose'],
    workerHints: [
      'Use two role-specific evidence items and access.compare_evidence before proposing authorization impact.',
      'Do not claim IDOR solely from different response bodies; explain the unauthorized object or action.',
    ],
    safetyNotes: ['No destructive state changes', 'Cross-role tests that mutate state are R3'],
    references: ['OWASP Broken Access Control', 'Bug bounty IDOR report workflow'],
    tags: ['authz', 'idor', 'role-diff'],
  },
  {
    id: 'oast.ssrffallback',
    name: 'Out-of-Band SSRF Callback Review',
    category: 'oast',
    status: 'ready',
    description: 'Use a local OAST callback as evidence for approved blind SSRF or webhook validation.',
    vulnerabilityClasses: ['CWE-918', 'SSRF', 'Blind callback'],
    requiredEvidence: ['oast_callback', 'http_exchange'],
    recommendedTools: ['oast.start_session', 'oast.record_callback', 'finding.propose'],
    workerHints: [
      'Start OAST inbox first and wait for callback evidence; do not embed OAST payloads in live targets without R3 approval.',
      'A callback proves interaction, not impact; link it with the initiating request evidence.',
    ],
    safetyNotes: ['Live payload injection is R3', 'No data exfiltration payloads'],
    references: ['OAST validation pattern', 'SSRF evidence workflow'],
    tags: ['ssrf', 'oast', 'blind'],
  },
  {
    id: 'web.missing-security-headers',
    name: 'Security Header Evidence Template',
    category: 'web',
    status: 'ready',
    description: 'Turn bounded security-header scan evidence into a low-risk web hardening finding when impact is appropriate.',
    vulnerabilityClasses: ['CWE-693', 'Security Misconfiguration'],
    requiredEvidence: ['command_output', 'http_exchange'],
    recommendedTools: ['scanner.run_template:web.security_headers', 'finding.propose'],
    workerHints: [
      'Use web.security_headers evidence; avoid over-stating severity without exploitability context.',
      'Prefer remediation guidance with exact missing headers from evidence.',
    ],
    safetyNotes: ['Passive HTTP only'],
    references: ['Mozilla Observatory style checks'],
    tags: ['headers', 'hardening', 'web'],
  },
  {
    id: 'web.cookie-flags',
    name: 'Cookie Flag Review Template',
    category: 'web',
    status: 'ready',
    description: 'Review Set-Cookie metadata for Secure, HttpOnly, and SameSite gaps without storing cookie values.',
    vulnerabilityClasses: ['CWE-614', 'CWE-1004', 'Session Hardening'],
    requiredEvidence: ['command_output', 'http_exchange'],
    recommendedTools: ['scanner.run_template:web.cookie_flags', 'finding.propose'],
    workerHints: [
      'Use cookie_flags output and cite cookie names only; never request or store cookie values.',
      'Severity depends on session sensitivity and transport context.',
    ],
    safetyNotes: ['Cookie values are redacted', 'Passive response review only'],
    references: ['OWASP Session Management Cheat Sheet'],
    tags: ['cookies', 'session', 'web'],
  },
  {
    id: 'sast.semgrep-to-finding',
    name: 'SAST Evidence To Finding',
    category: 'sast',
    status: 'ready',
    description: 'Convert local SAST evidence into a finding only after route, sink, and impact evidence are linked.',
    vulnerabilityClasses: ['SAST triage', 'Code evidence'],
    requiredEvidence: ['command_output', 'file_hash'],
    recommendedTools: ['scanner.run_template:sast.semgrep.baseline', 'finding.propose'],
    workerHints: [
      'Treat static alerts as hypotheses; do not report until affected code and impact evidence are linked.',
      'Keep source snippets bounded and redacted.',
    ],
    safetyNotes: ['No source upload by default', 'No automatic code changes'],
    references: ['AutoRedTeam-Orchestrator SARIF surface'],
    tags: ['sast', 'semgrep', 'sarif'],
  },
  {
    id: 'mobile.android-manifest-review',
    name: 'Android Manifest Evidence Template',
    category: 'mobile',
    status: 'external_required',
    description: 'Review APK manifest evidence for exported components, permissions, and debuggable flags.',
    vulnerabilityClasses: ['Mobile misconfiguration', 'Android exported component'],
    requiredEvidence: ['command_output'],
    recommendedTools: ['android.manifest.import', 'scanner.run_template:mobile.apk.manifest', 'finding.propose'],
    workerHints: [
      'Use android.manifest.import first when AndroidManifest.xml content is available.',
      'Use this only with APK evidence or approved mobile artifacts.',
      'Dynamic exploitation or device interaction remains R3.',
    ],
    safetyNotes: ['Static review first', 'No device persistence'],
    references: ['DragonJAR Android-Pentesting-Skill'],
    tags: ['android', 'apk', 'manifest'],
  },
  {
    id: 'cloud.iam-policy-review',
    name: 'Cloud IAM Policy Review Template',
    category: 'cloud',
    status: 'ready',
    description: 'Review imported cloud IAM policy evidence for wildcard admin, PassRole, AssumeRole, and mutation-risk statements.',
    vulnerabilityClasses: ['Cloud IAM misconfiguration', 'Least privilege gap', 'Privilege escalation path'],
    requiredEvidence: ['command_output'],
    recommendedTools: ['cloud.iam.import', 'finding.propose'],
    workerHints: [
      'Use cloud.iam.import evidence before proposing cloud IAM findings.',
      'Do not ask for raw cloud credentials; IAM policy JSON and vault references are the supported inputs.',
      'Treat policy-risk findings as candidates until business context and affected principal/resource scope are reviewed.',
    ],
    safetyNotes: ['Read-only artifact review', 'No cloud API calls or key material required'],
    references: ['AWS IAM least privilege review', 'Enterprise cloud audit workflow'],
    tags: ['cloud', 'iam', 'policy'],
  },
  {
    id: 'identity.graph-path-review',
    name: 'Identity Graph Path Review Template',
    category: 'auth',
    status: 'ready',
    description: 'Review imported identity graph evidence for high-value privilege edges and roastable/delegation-risk identities.',
    vulnerabilityClasses: ['Active Directory privilege path', 'Identity misconfiguration', 'Least privilege gap'],
    requiredEvidence: ['command_output'],
    recommendedTools: ['identity.graph.import', 'finding.propose'],
    workerHints: [
      'Use identity.graph.import evidence before proposing identity-path findings.',
      'Do not request password spraying, credential extraction, or lateral movement execution.',
      'Treat graph signals as candidates until an operator validates context and affected business scope.',
    ],
    safetyNotes: ['Read-only graph import', 'No active lateral movement', 'No credential attacks'],
    references: ['BloodHound-style identity path review', 'Enterprise internal assessment module'],
    tags: ['identity', 'ad', 'bloodhound'],
  },
  {
    id: 'auth.multi-tenant-bypass',
    name: 'Multi-Tenant Authorization Evidence Template',
    category: 'auth',
    status: 'ready',
    description: 'Collect role and tenant differential evidence before proposing high-severity tenant-boundary findings.',
    vulnerabilityClasses: ['CWE-639', 'CWE-862', 'CWE-863', 'BOLA', 'Broken Access Control', 'Tenant isolation failure'],
    requiredEvidence: ['http_exchange', 'command_output'],
    recommendedTools: ['credential.use_placeholder', 'http.request', 'access.compare_evidence', 'finding.propose'],
    workerHints: [
      'Use baseline and comparison evidence from distinct authorized roles or tenants before claiming tenant-boundary impact.',
      'Prioritize unauthorized object/action proof over status-code differences or cosmetic response changes.',
      'Mutating cross-tenant checks are R3 and need explicit approval even when this template is enabled.',
    ],
    safetyNotes: ['Use placeholder credentials only', 'No destructive tenant actions', 'No raw tokens or cookies in evidence'],
    references: ['OWASP API Security Top 10', 'Enterprise access-control testing workflow'],
    tags: ['authz', 'tenant', 'bola', 'idor', 'high-impact'],
  },
  {
    id: 'api.graphql-field-authz',
    name: 'GraphQL Field Authorization Evidence Template',
    category: 'api',
    status: 'ready',
    description: 'Review GraphQL schema, operation, and role-differential evidence for field or resolver authorization gaps.',
    vulnerabilityClasses: ['GraphQL authorization bypass', 'CWE-862', 'CWE-863', 'Excessive data exposure'],
    requiredEvidence: ['http_exchange', 'command_output'],
    recommendedTools: ['http.request', 'credential.use_placeholder', 'access.compare_evidence', 'finding.propose'],
    workerHints: [
      'Do not report introspection alone; link exposed fields or resolver behavior to unauthorized data or action impact.',
      'Use role-differential evidence when a field or mutation should be restricted.',
      'Redact bearer tokens, operation variables, and user identifiers before report use.',
    ],
    safetyNotes: ['No token disclosure', 'No destructive mutations without R3 approval', 'No schema dumping outside authorized scope'],
    references: ['OWASP GraphQL Security Cheat Sheet', 'OWASP API Security Top 10'],
    tags: ['graphql', 'api', 'authz', 'resolver'],
  },
  {
    id: 'oauth.oidc-flow-review',
    name: 'OAuth OIDC Flow Evidence Template',
    category: 'oauth',
    status: 'ready',
    description: 'Collect redacted OAuth/OIDC configuration and browser-flow evidence for identity misbinding or unsafe token handling.',
    vulnerabilityClasses: ['OAuth misconfiguration', 'OIDC flow weakness', 'CWE-346', 'CWE-601', 'Session/token handling'],
    requiredEvidence: ['http_exchange', 'screenshot'],
    recommendedTools: ['browser.navigate', 'http.request', 'credential.use_placeholder', 'finding.propose'],
    workerHints: [
      'Capture authorization and callback flow evidence without storing authorization codes, tokens, cookies, or raw identity claims.',
      'Bind risk to redirect trust, audience/client mismatch, missing state/nonce evidence, or token exposure context.',
      'Do not simulate phishing or malicious identity-provider behavior through this template.',
    ],
    safetyNotes: ['Token and code values must be redacted', 'No phishing flows', 'No credential replay'],
    references: ['OAuth 2.0 Security Best Current Practice', 'OIDC review workflow'],
    tags: ['oauth', 'oidc', 'sso', 'identity'],
  },
  {
    id: 'web.ssrf-impact-triage',
    name: 'SSRF Impact Triage Template',
    category: 'web',
    status: 'ready',
    description: 'Separate blind interaction evidence from confirmed impact for authorized SSRF and webhook testing.',
    vulnerabilityClasses: ['CWE-918', 'SSRF', 'Blind callback', 'Cloud metadata exposure risk'],
    requiredEvidence: ['http_exchange', 'oast_callback'],
    recommendedTools: ['http.request', 'oast.start_session', 'oast.record_callback', 'finding.propose'],
    workerHints: [
      'A callback proves interaction, not impact; request additional safe evidence before claiming cloud or internal reachability.',
      'Classify impact by reachable asset class and data boundary evidence, not by payload novelty.',
      'Do not request data exfiltration, metadata-token retrieval, or internal port sweeping.',
    ],
    safetyNotes: ['OAST use is R3 unless preapproved', 'No data exfiltration payloads', 'No internal service enumeration'],
    references: ['SSRF evidence workflow', 'OAST validation pattern'],
    tags: ['ssrf', 'oast', 'impact-triage', 'high-impact'],
  },
  {
    id: 'web.rce-deserialization-triage',
    name: 'RCE Deserialization Evidence Template',
    category: 'web',
    status: 'external_required',
    description: 'Triage high-impact RCE or unsafe deserialization signals with non-destructive, approval-gated evidence.',
    vulnerabilityClasses: ['CWE-94', 'CWE-502', 'RCE', 'Unsafe deserialization', 'Template injection'],
    requiredEvidence: ['http_exchange', 'command_output'],
    recommendedTools: ['http.request', 'scanner.run_template', 'shell.run_sandboxed', 'finding.propose'],
    workerHints: [
      'Treat RCE/deserialization as critical hypotheses only when version, sink, route, and bounded validation evidence align.',
      'Prefer non-destructive proof such as safe marker output, stack trace, local fixture reproduction, or vendor advisory mapping.',
      'Do not request reverse shells, persistence, destructive commands, or sensitive file reads.',
    ],
    safetyNotes: ['Dynamic validation is R3', 'No reverse shell or persistence', 'No sensitive file access'],
    references: ['OWASP Code Injection', 'CVE/advisory impact validation workflow'],
    tags: ['rce', 'deserialization', 'critical', 'approval-required'],
  },
  {
    id: 'web.file-upload-path-traversal',
    name: 'File Upload And Path Traversal Evidence Template',
    category: 'web',
    status: 'ready',
    description: 'Review file upload, download, and path traversal evidence for unauthorized file access or executable content risk.',
    vulnerabilityClasses: ['CWE-22', 'CWE-23', 'CWE-434', 'Path traversal', 'Unrestricted file upload'],
    requiredEvidence: ['http_exchange', 'screenshot'],
    recommendedTools: ['http.request', 'browser.navigate', 'scanner.run_template', 'finding.propose'],
    workerHints: [
      'Prioritize unauthorized file read/write, content-type bypass, storage exposure, and executable upload impact.',
      'Use benign marker files and screenshots where possible; avoid accessing sensitive system or user files.',
      'State-changing upload or delete checks are R3 unless explicitly allowed by policy.',
    ],
    safetyNotes: ['No sensitive file reads', 'No malware upload', 'No destructive delete/overwrite checks'],
    references: ['OWASP File Upload Cheat Sheet', 'OWASP Path Traversal guidance'],
    tags: ['upload', 'path-traversal', 'web', 'high-impact'],
  },
  {
    id: 'web.injection-impact-triage',
    name: 'Injection Impact Triage Template',
    category: 'web',
    status: 'ready',
    description: 'Turn SQL/NoSQL/command/template injection signals into evidence-ranked candidate findings without unsafe payloads.',
    vulnerabilityClasses: ['CWE-89', 'CWE-78', 'CWE-74', 'SQL injection', 'NoSQL injection', 'Command injection', 'Template injection'],
    requiredEvidence: ['http_exchange', 'command_output'],
    recommendedTools: ['http.request', 'scanner.run_template', 'finding.propose'],
    workerHints: [
      'Separate scanner signal, application error evidence, timing signal, and confirmed data-impact evidence.',
      'Prefer bounded, non-destructive proof and local fixture reproduction before high-confidence claims.',
      'Do not request destructive queries, data dumping, shell execution, or credential extraction.',
    ],
    safetyNotes: ['No data dumping', 'No destructive queries', 'Dynamic proof is R3 when it changes state or executes commands'],
    references: ['OWASP Injection', 'DAST evidence triage workflow'],
    tags: ['injection', 'sqli', 'command-injection', 'high-impact'],
  },
  {
    id: 'secrets.exposure-review',
    name: 'Secrets Exposure Evidence Template',
    category: 'secrets',
    status: 'external_required',
    description: 'Review source, artifact, log, and response evidence for exposed secrets without copying secret values.',
    vulnerabilityClasses: ['Secret exposure', 'CWE-200', 'CWE-798', 'Credential disclosure'],
    requiredEvidence: ['command_output', 'file_hash'],
    recommendedTools: ['scanner.run_template', 'shell.run_sandboxed', 'finding.propose'],
    workerHints: [
      'Report secret type, location, affected system, and rotation priority; never repeat the full secret value.',
      'Prioritize live-looking cloud, CI/CD, signing, and production credentials above test placeholders.',
      'Do not validate secrets by logging in or calling third-party services unless separately authorized.',
    ],
    safetyNotes: ['No raw secret values in evidence or reports', 'No credential use', 'Rotation guidance required'],
    references: ['Secret scanning workflow', 'Supply-chain incident handling'],
    tags: ['secrets', 'supply-chain', 'credentials', 'rotation'],
  },
  {
    id: 'cloud.storage-public-exposure',
    name: 'Cloud Storage Exposure Evidence Template',
    category: 'cloud',
    status: 'ready',
    description: 'Review cloud storage and object exposure with read-only metadata and redacted sample evidence.',
    vulnerabilityClasses: ['Cloud storage exposure', 'CWE-200', 'Security misconfiguration', 'Data exposure'],
    requiredEvidence: ['command_output', 'http_exchange'],
    recommendedTools: ['cloud.iam.import', 'http.request', 'scanner.run_template', 'finding.propose'],
    workerHints: [
      'Prioritize public write, public sensitive read, policy wildcard, and unauthenticated listing evidence.',
      'Use metadata, object names, hashes, or redacted samples; do not download or expose sensitive data.',
      'Bind severity to business data sensitivity and effective access policy, not just bucket existence.',
    ],
    safetyNotes: ['Read-only review', 'No bulk download', 'No sensitive sample reproduction'],
    references: ['Cloud storage security review', 'CSPM evidence workflow'],
    tags: ['cloud', 'storage', 'exposure', 'cspm'],
  },
  {
    id: 'container.k8s-rbac-risk',
    name: 'Kubernetes RBAC And Container Risk Template',
    category: 'container',
    status: 'external_required',
    description: 'Map Kubernetes RBAC, workload, and container posture signals into evidence-backed candidate findings.',
    vulnerabilityClasses: ['Kubernetes RBAC risk', 'Privileged container', 'Secret mount exposure', 'Cloud-native misconfiguration'],
    requiredEvidence: ['command_output', 'file_hash'],
    recommendedTools: ['scanner.run_template', 'shell.run_sandboxed', 'finding.propose'],
    workerHints: [
      'Prioritize cluster-admin paths, privileged pods, hostPath mounts, exposed dashboards, and secret access paths.',
      'Use read-only manifest or scanner evidence; do not request kubectl exec, apply, delete, or secret reads.',
      'Link container risk to affected namespace, service account, workload, and business exposure.',
    ],
    safetyNotes: ['Read-only manifests first', 'No production cluster mutations', 'No secret extraction'],
    references: ['CIS Kubernetes Benchmark', 'Prowler/cloud-native posture workflow'],
    tags: ['kubernetes', 'container', 'rbac', 'cloud-native'],
  },
  {
    id: 'supply-chain.sbom-vulnerable-component',
    name: 'SBOM Vulnerable Component Evidence Template',
    category: 'supply_chain',
    status: 'external_required',
    description: 'Convert SBOM/SCA evidence into prioritized vulnerability lifecycle work only when reachability and context support impact.',
    vulnerabilityClasses: ['Vulnerable dependency', 'CVE exposure', 'Supply chain risk', 'Outdated component'],
    requiredEvidence: ['command_output', 'file_hash'],
    recommendedTools: ['scanner.run_template', 'shell.run_sandboxed', 'finding.propose'],
    workerHints: [
      'Prioritize KEV, EPSS, known exploited, internet-facing, auth-bypass, and RCE-class dependency risk.',
      'Do not auto-confirm every CVE; link component version, deployment context, reachability, and mitigation state.',
      'Attach remediation as upgrade, mitigation, compensating control, and retest criteria.',
    ],
    safetyNotes: ['No exploit execution by default', 'No public disclosure workflow without owner review'],
    references: ['Dependency-Track component risk model', 'DefectDojo vulnerability lifecycle', 'CVE advisory workflow'],
    tags: ['sbom', 'sca', 'cve', 'supply-chain'],
  },
  {
    id: 'network.exposed-service-risk',
    name: 'Exposed Service Risk Evidence Template',
    category: 'network',
    status: 'external_required',
    description: 'Triage scoped service exposure evidence into high-impact findings for admin, identity, database, and cloud surfaces.',
    vulnerabilityClasses: ['Exposed service', 'Management interface exposure', 'TLS/DNS misconfiguration', 'Attack surface risk'],
    requiredEvidence: ['command_output', 'http_exchange'],
    recommendedTools: ['scanner.run_template', 'http.request', 'shell.run_sandboxed', 'finding.propose'],
    workerHints: [
      'Escalate externally exposed admin panels, identity providers, cloud consoles, databases, and unauthenticated APIs.',
      'Use scoped inventory and fingerprint evidence; do not brute force, spray, or exploit services.',
      'Map each exposure to asset owner, authentication state, network boundary, and remediation path.',
    ],
    safetyNotes: ['Scoped inventory only', 'No brute force', 'No broad unauthenticated exploitation'],
    references: ['ProjectDiscovery inventory workflow', 'Faraday asset/finding workflow'],
    tags: ['network', 'exposure', 'inventory', 'external-surface'],
  },
  {
    id: 'ai.prompt-tool-injection',
    name: 'AI Prompt And Tool Injection Evidence Template',
    category: 'ai_security',
    status: 'external_required',
    description: 'Evaluate agentic AI systems for prompt/tool injection impact using external eval output and governed evidence.',
    vulnerabilityClasses: ['Prompt injection', 'Tool injection', 'MCP permission risk', 'Agent data-boundary failure'],
    requiredEvidence: ['command_output', 'http_exchange', 'screenshot'],
    recommendedTools: ['scanner.run_template', 'browser.navigate', 'http.request', 'finding.propose'],
    workerHints: [
      'Treat injection as high risk only when it causes unauthorized tool use, policy bypass, data exposure, or cross-tenant action.',
      'Use imported eval/scanner evidence and operator review; do not let the model score its own success.',
      'Redact prompts, outputs, tool traces, and user data before report or export.',
    ],
    safetyNotes: ['No prompt theft', 'No unsafe tool execution', 'No unredacted AI transcript export'],
    references: ['promptfoo red-team eval', 'PyRIT scorer workflow', 'Tencent AI-Infra-Guard MCP/skill scan'],
    tags: ['ai-security', 'prompt-injection', 'mcp', 'agent-security'],
  },
];

export function listPocTemplates(): PocTemplate[] {
  return POC_TEMPLATES.map(cloneTemplate);
}

export function getPocTemplate(templateId: string): PocTemplate | undefined {
  const template = POC_TEMPLATES.find((item) => item.id === templateId);
  return template ? cloneTemplate(template) : undefined;
}

function cloneTemplate(template: PocTemplate): PocTemplate {
  return {
    ...template,
    vulnerabilityClasses: [...template.vulnerabilityClasses],
    requiredEvidence: [...template.requiredEvidence],
    recommendedTools: [...template.recommendedTools],
    workerHints: [...template.workerHints],
    safetyNotes: [...template.safetyNotes],
    references: [...template.references],
    tags: [...template.tags],
  };
}
