import type { DomainSkill } from '../domain/types.js';

export const DOMAIN_SKILLS: DomainSkill[] = [
  {
    id: 'web.bounty-workspace',
    name: 'Web Bug Bounty Workspace',
    category: 'web',
    status: 'ready',
    description: 'Evidence-first web application assessment for authorized bounty or SRC scope.',
    rigidUseCases: ['HTTP evidence capture', 'safe scanner templates', 'finding proposal and report formatting'],
    excludedUseCases: ['generic pentest playbooks', 'credential attacks', 'destructive exploitation'],
    recommendedTools: ['http.request', 'scanner.run_template', 'finding.propose', 'evidence.add'],
    requiredToolboxProfiles: ['builtin.web'],
    workerHints: [
      'Stay inside the authorized web scope and collect durable HTTP evidence before any finding proposal.',
      'Prefer browser/proxy captures and built-in safe templates before requesting higher-risk validation.',
    ],
    riskNotes: ['R3 validation still requires approval; R4 remains blocked.'],
    references: ['Cairn graph discipline', 'WonderSuite browser/proxy UX', 'Bug bounty report workflow'],
  },
  {
    id: 'web.high-risk-triage',
    name: 'Aggressive Web High-Risk Triage',
    category: 'web',
    status: 'ready',
    description: 'Enterprise web triage that prioritizes exploitable high-impact classes inside a signed assessment scope.',
    rigidUseCases: [
      'high-impact web vulnerability hypothesis ranking',
      'SSRF, RCE, injection, upload, path traversal, and auth-impact evidence planning',
      'escalating weak evidence into concrete validation gates',
    ],
    excludedUseCases: ['destructive exploitation', 'credential theft', 'data exfiltration', 'persistence', 'out-of-scope testing'],
    recommendedTools: [
      'http.request',
      'browser.navigate',
      'scanner.run_template',
      'access.compare_evidence',
      'oast.start_session',
      'finding.propose',
    ],
    requiredToolboxProfiles: ['builtin.web'],
    workerHints: [
      'Bias exploration toward high-impact web classes before low-value hardening findings.',
      'If evidence is weak, request the next bounded in-scope observation instead of downshifting to informational output.',
      'Use R3 approval only for bounded validation that materially changes confidence or impact.',
    ],
    riskNotes: [
      'Aggressive means high-impact prioritization inside ROE, not bypassing scope, approvals, or redaction.',
      'R4 behaviors remain denied by default even when this skill is enabled; break-glass execution still needs scope token and approval.',
    ],
    references: ['PentestGPT benchmark discipline', 'Z3r0 controlled penetration engineer role', 'Burp/ZAP high-impact workflow'],
  },
  {
    id: 'web.browser-proxy-runner',
    name: 'Browser Proxy Runner Workflow',
    category: 'web',
    status: 'external_required',
    description: 'Authenticated browser, proxy, HAR, trace, screenshot, and replay workflow for real web assessment evidence.',
    rigidUseCases: ['rendered browser state capture', 'authenticated session evidence', 'proxy/HAR replay and screenshot proof'],
    excludedUseCases: ['implicit TLS interception', 'raw cookie disclosure to Workers', 'unbounded crawling', 'out-of-scope navigation'],
    recommendedTools: ['browser.navigate', 'http.request', 'access.compare_evidence', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: ['desktop.browser-runner'],
    workerHints: [
      'Prefer rendered browser/proxy evidence when JavaScript, session state, or user-visible impact matters.',
      'Request screenshots or replay bundles as proof, but do not ask for raw cookies, tokens, or browser profiles.',
      'Keep each navigation tied to the run target and stop when scope gates block movement.',
    ],
    riskNotes: ['TLS MITM and authenticated browser profiles require explicit local runner controls before execution.'],
    references: ['Z3r0 Docker sandbox tooling', 'Playwright trace workflow', 'Burp/ZAP proxy evidence model'],
  },
  {
    id: 'api.authz-workflow',
    name: 'Enterprise API Authorization Workflow',
    category: 'api',
    status: 'ready',
    description: 'Aggressive API authn/authz and multi-tenant review with role-differential evidence requirements.',
    rigidUseCases: ['API object authorization review', 'multi-tenant boundary checks', 'role-differential evidence comparison'],
    excludedUseCases: ['credential attacks', 'state-damaging mutations', 'unapproved cross-tenant actions', 'rate-limit abuse'],
    recommendedTools: ['credential.use_placeholder', 'http.request', 'access.compare_evidence', 'finding.propose'],
    requiredToolboxProfiles: ['builtin.web'],
    workerHints: [
      'Prioritize broken object, function, property, and tenant-level authorization over cosmetic API issues.',
      'Use same-endpoint baseline/comparison evidence before proposing high-severity access-control impact.',
      'Treat authenticated mutation checks as R3 unless the run policy explicitly downgrades the action.',
    ],
    riskNotes: ['Use placeholder credentials only; never request raw tokens or passwords in prompts or reports.'],
    references: ['OWASP API Security Top 10', 'Z3r0 evidence and manual review workflow', 'PentestAgent black-box workflow'],
  },
  {
    id: 'api.graphql-oauth-review',
    name: 'GraphQL And OAuth Review',
    category: 'api',
    status: 'ready',
    description: 'GraphQL, OAuth, OIDC, and API discovery review for enterprise identity-backed applications.',
    rigidUseCases: ['GraphQL schema and resolver authorization evidence', 'OAuth/OIDC flow review', 'token-handling and redirect evidence'],
    excludedUseCases: ['token theft', 'phishing', 'malicious redirect exploitation', 'credential replay'],
    recommendedTools: ['http.request', 'browser.navigate', 'credential.use_placeholder', 'access.compare_evidence', 'finding.propose'],
    requiredToolboxProfiles: ['builtin.web'],
    workerHints: [
      'Look for resolver-level authorization gaps, excessive field exposure, and identity-flow misbinding.',
      'For OAuth/OIDC issues, capture configuration and flow evidence without storing bearer tokens.',
      'Do not treat introspection alone as a vulnerability; bind it to exposed fields, roles, or business impact.',
    ],
    riskNotes: ['OAuth evidence must redact tokens, codes, cookies, and user identifiers before report use.'],
    references: ['OWASP API Security Top 10', 'OWASP GraphQL Security Cheat Sheet', 'OAuth 2.0/OIDC review practice'],
  },
  {
    id: 'mobile.android-apk',
    name: 'Android APK Assessment',
    category: 'mobile',
    status: 'ready',
    description: 'Android package triage and dynamic probe planning for authorized mobile targets.',
    rigidUseCases: ['APK manifest review', 'static package triage', 'Frida probe planning'],
    excludedUseCases: ['device persistence', 'credential extraction', 'unapproved live device actions'],
    recommendedTools: ['android.manifest.import', 'scanner.run_template:mobile.apk.manifest', 'scanner.run_template:mobile.frida.probe'],
    requiredToolboxProfiles: [],
    workerHints: [
      'Start with android.manifest.import for static package, permission, and exported component evidence.',
      'Treat APK paths, package IDs, and device probes as separate evidence-bearing steps.',
      'Use Android-specific templates only when the target is an APK, package, emulator, or approved test device.',
    ],
    riskNotes: ['Dynamic device actions are R3 unless explicitly downgraded by policy.'],
    references: ['DragonJAR Android-Pentesting-Skill'],
  },
  {
    id: 'sast.semgrep-baseline',
    name: 'Source SAST Baseline',
    category: 'sast',
    status: 'external_required',
    description: 'Source-code baseline triage with Semgrep-style evidence and SARIF-friendly output.',
    rigidUseCases: ['source tree triage', 'safe static rules', 'evidence-backed code finding drafts'],
    excludedUseCases: ['secret exfiltration', 'unbounded repository crawling', 'auto-fixing production code'],
    recommendedTools: ['scanner.run_template:sast.semgrep.baseline', 'shell.run_sandboxed'],
    requiredToolboxProfiles: ['local.sast'],
    workerHints: [
      'Use static findings as hypotheses until affected code, route, and impact evidence are linked.',
      'Prefer small targeted scans over broad repository sweeps.',
    ],
    riskNotes: ['Do not include raw secrets in evidence; redact before storing or reporting.'],
    references: ['AutoRedTeam-Orchestrator CI/SARIF surface', 'CAI eval-oriented framework'],
  },
  {
    id: 'cloud.iam-audit',
    name: 'Cloud IAM Audit',
    category: 'cloud',
    status: 'ready',
    description: 'Cloud account and IAM posture review for approved enterprise assessments.',
    rigidUseCases: ['IAM policy JSON review', 'read-only cloud inventory', 'policy-risk evidence'],
    excludedUseCases: ['key harvesting', 'destructive cloud actions', 'privilege escalation execution'],
    recommendedTools: ['cloud.iam.import', 'credential.use_placeholder', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: [],
    workerHints: [
      'Use cloud.iam.import first when IAM policy JSON is available.',
      'Use vault references or placeholders only; never ask the operator to paste cloud secrets into prompts.',
      'Keep cloud actions read-only unless a future policy explicitly approves a bounded validation.',
    ],
    riskNotes: ['Credential material must remain local and must not be written into graph hints or reports.'],
    references: ['Enterprise edition private worker node requirement'],
  },
  {
    id: 'identity.ad-paths',
    name: 'AD Identity Path Review',
    category: 'identity',
    status: 'ready',
    description: 'Active Directory and identity-path review for internal authorized environments.',
    rigidUseCases: ['read-only identity graph import', 'privilege path evidence review', 'control validation notes'],
    excludedUseCases: ['lateral movement execution', 'password spraying', 'persistence'],
    recommendedTools: ['identity.graph.import', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: [],
    workerHints: [
      'Use identity.graph.import first when BloodHound or identity graph JSON is available.',
      'Separate imported identity graph evidence from any active validation intent.',
      'Treat lateral movement, password attacks, and persistence as prohibited unless future policy changes.',
    ],
    riskNotes: ['Default posture is review-only; active AD validation is R3 or blocked.'],
    references: ['Enterprise internal assessment module'],
  },
  {
    id: 'cloud.k8s-container-posture',
    name: 'Kubernetes And Container Posture',
    category: 'container',
    status: 'external_required',
    description: 'Kubernetes, container, and cloud-native posture review for high-impact enterprise exposure.',
    rigidUseCases: ['Kubernetes RBAC review', 'container image and runtime posture', 'cloud-native privilege and network exposure evidence'],
    excludedUseCases: ['cluster write actions', 'pod escape execution', 'secret extraction', 'destructive workload changes'],
    recommendedTools: ['scanner.run_template', 'shell.run_sandboxed', 'cloud.iam.import', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: ['container.cloud-posture'],
    workerHints: [
      'Prioritize exposed control planes, broad RBAC, privileged workloads, secret mounts, and public services.',
      'Use read-only manifests, scan output, or imported posture evidence before proposing container findings.',
      'Do not request kubectl apply/delete, exec into production workloads, or secret material.',
    ],
    riskNotes: ['Cloud and cluster actions are read-only unless separately approved and bounded by ROE.'],
    references: ['Prowler posture workflow', 'CIS Kubernetes Benchmark', 'Z3r0 sandbox binding model'],
  },
  {
    id: 'supply-chain.sca-secrets',
    name: 'Supply Chain And Secrets Exposure',
    category: 'supply_chain',
    status: 'external_required',
    description: 'SBOM, dependency, CI/CD, and secrets review focused on exploitable enterprise supply-chain risk.',
    rigidUseCases: ['SCA and SBOM triage', 'secret exposure review', 'CI/CD privilege and artifact trust evidence'],
    excludedUseCases: ['secret value disclosure', 'secret reuse', 'publishing advisories without owner review', 'pipeline dispatch'],
    recommendedTools: ['scanner.run_template', 'shell.run_sandboxed', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: ['local.sast'],
    workerHints: [
      'Prioritize reachable critical/high dependency risk, exposed secrets, and CI privileges over raw CVE volume.',
      'Report secret type, location, and rotation guidance without repeating the secret value.',
      'Treat dependency alerts as candidates until version, reachability, exploitability, and business context are linked.',
    ],
    riskNotes: ['No raw secrets in evidence, hints, reports, exports, or cross-run memory.'],
    references: ['Dependency-Track component risk model', 'Semgrep/SARIF workflow', 'GitHub secret scanning practice'],
  },
  {
    id: 'network.external-surface-baseline',
    name: 'External Surface Baseline',
    category: 'network',
    status: 'external_required',
    description: 'Scoped external exposure baseline for internet-facing hosts, TLS, DNS, and service inventory.',
    rigidUseCases: ['scoped host/service inventory', 'TLS and DNS evidence', 'exposure prioritization for high-impact services'],
    excludedUseCases: ['internet-wide scanning', 'brute force', 'exploit spraying', 'destructive service checks'],
    recommendedTools: ['scanner.run_template', 'http.request', 'shell.run_sandboxed', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: ['container.web-recon'],
    workerHints: [
      'Map exposed services only inside the allowlisted assets and rate limits.',
      'Escalate externally exposed admin, identity, cloud, and management surfaces above ordinary banner issues.',
      'Do not request broad port sweeps or vulnerability blasting without an explicit allowlist and approval path.',
    ],
    riskNotes: ['External scanners must remain template-allowlisted and fail closed by default.'],
    references: ['ProjectDiscovery Nuclei/httpx/tlsx ecosystem', 'Z3r0 controlled sandbox execution', 'Faraday asset model'],
  },
  {
    id: 'ai.agent-infra-security',
    name: 'AI Agent Infrastructure Security',
    category: 'ai_security',
    status: 'external_required',
    description: 'AI application, MCP, skill, tool, and agent-infra red-team review for enterprise AI deployments.',
    rigidUseCases: ['AI infra fingerprint review', 'MCP/skill manifest risk checks', 'prompt/tool injection evidence', 'LLM eval import'],
    excludedUseCases: ['jailbreak-only scoring without business impact', 'prompt theft', 'tool poisoning execution', 'unsafe autonomous actions'],
    recommendedTools: ['scanner.run_template', 'http.request', 'browser.navigate', 'evidence.add', 'finding.propose'],
    requiredToolboxProfiles: ['ai.security-eval'],
    workerHints: [
      'Prioritize tool invocation abuse, data boundary failure, unsafe MCP/skill permissions, and agent workflow risk.',
      'Treat jailbreak or prompt-injection observations as findings only when tied to unauthorized tool use, data exposure, or policy bypass impact.',
      'Import eval/scanner results as evidence; do not let the model self-score its own success.',
    ],
    riskNotes: ['AI red-team eval must keep prompts, outputs, and tool traces redacted before external reporting.'],
    references: ['Tencent AI-Infra-Guard', 'promptfoo red-team eval', 'PyRIT scorer/orchestrator pattern'],
  },
  {
    id: 'reporting.commercial-handoff',
    name: 'Commercial Report Handoff',
    category: 'reporting',
    status: 'ready',
    description: 'Submission-ready report and export discipline for Bug Bounty, SRC, and enterprise delivery.',
    rigidUseCases: ['confirmed-only report bundle', 'safe evidence index', 'operator-reviewed submission package'],
    excludedUseCases: ['auto-submit without review', 'marketing-style report prose', 'raw local traffic upload'],
    recommendedTools: ['finding.propose', 'evidence.add'],
    requiredToolboxProfiles: [],
    workerHints: [
      'Treat report output as a delivery gate: confirmed findings must cite same-run evidence.',
      'Do not include raw_local_only evidence or credentials in customer-facing report bundles.',
      'Use platform report formats only after operator validation, not as Worker self-confirmation.',
    ],
    riskNotes: ['External submission remains operator-controlled; cloud sync accepts only redacted or safe evidence.'],
    references: ['pentest-agents submission gate', 'AIDA/CyberStrike reporting workflow', 'ai-engineering-from-scratch Ship It artifact rule'],
  },
  {
    id: 'ctf.flag-submit',
    name: 'CTF Flag Submission',
    category: 'ctf',
    status: 'planned',
    description: 'Competition-specific flag submission adapter inspired by Cairn-style minimal skills.',
    rigidUseCases: ['flag format validation', 'submission gate', 'scoreboard evidence'],
    excludedUseCases: ['general exploit methodology', 'generic CTF playbooks', 'unapproved external submission'],
    recommendedTools: ['evidence.add'],
    requiredToolboxProfiles: [],
    workerHints: [
      'Use this only when the run goal explicitly includes an approved competition flag submission target.',
      'Do not infer exploit steps from the skill; it is a submission gate, not a playbook.',
    ],
    riskNotes: ['External submissions must be operator-approved in a future adapter.'],
    references: ['Cairn flag submission skill'],
  },
];

export function listDomainSkills(): DomainSkill[] {
  return DOMAIN_SKILLS.map((skill) => cloneSkill(skill));
}

export function getDomainSkill(skillId: string): DomainSkill | undefined {
  const skill = DOMAIN_SKILLS.find((item) => item.id === skillId);
  return skill ? cloneSkill(skill) : undefined;
}

function cloneSkill(skill: DomainSkill): DomainSkill {
  return {
    ...skill,
    rigidUseCases: [...skill.rigidUseCases],
    excludedUseCases: [...skill.excludedUseCases],
    recommendedTools: [...skill.recommendedTools],
    requiredToolboxProfiles: [...skill.requiredToolboxProfiles],
    workerHints: [...skill.workerHints],
    riskNotes: [...skill.riskNotes],
    references: [...skill.references],
  };
}
